// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: apikeys.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countAPIKeys = `-- name: CountAPIKeys :one
SELECT COUNT(*)
FROM api_keys
WHERE ($1::text IS NULL OR user_id = $1)
  AND ($2::text IS NULL OR tenant_id = $2)
  AND ($3::text IS NULL OR status = $3)
  AND ($4::bool = FALSE OR (status = 'active' AND (expires_at IS NULL OR expires_at > NOW())))
`

type CountAPIKeysParams struct {
	UserID     pgtype.Text `json:"user_id"`
	TenantID   pgtype.Text `json:"tenant_id"`
	Status     pgtype.Text `json:"status"`
	ActiveOnly bool        `json:"active_only"`
}

func (q *Queries) CountAPIKeys(ctx context.Context, arg CountAPIKeysParams) (int64, error) {
	row := q.db.QueryRow(ctx, countAPIKeys,
		arg.UserID,
		arg.TenantID,
		arg.Status,
		arg.ActiveOnly,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createAPIKey = `-- name: CreateAPIKey :exec
INSERT INTO api_keys (id, user_id, name, key_prefix, key_hash, scopes, status, tenant_id, expires_at, last_used_at, created_at, revoked_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
`

type CreateAPIKeyParams struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	Scopes     []string           `json:"scopes"`
	Status     string             `json:"status"`
	TenantID   pgtype.Text        `json:"tenant_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) CreateAPIKey(ctx context.Context, arg CreateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, createAPIKey,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.KeyPrefix,
		arg.KeyHash,
		arg.Scopes,
		arg.Status,
		arg.TenantID,
		arg.ExpiresAt,
		arg.LastUsedAt,
		arg.CreatedAt,
		arg.RevokedAt,
	)
	return err
}

const deleteAPIKey = `-- name: DeleteAPIKey :exec
DELETE FROM api_keys
WHERE id = $1
`

func (q *Queries) DeleteAPIKey(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteAPIKey, id)
	return err
}

const deleteExpiredAPIKeys = `-- name: DeleteExpiredAPIKeys :execrows
DELETE FROM api_keys
WHERE expires_at IS NOT NULL AND expires_at < NOW() - INTERVAL '30 days'
`

func (q *Queries) DeleteExpiredAPIKeys(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredAPIKeys)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findAPIKeyByID = `-- name: FindAPIKeyByID :one
SELECT id, user_id, name, key_prefix, key_hash, scopes, status, tenant_id, expires_at, last_used_at, created_at, revoked_at
FROM api_keys
WHERE id = $1
`

func (q *Queries) FindAPIKeyByID(ctx context.Context, id string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, findAPIKeyByID, id)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Status,
		&i.TenantID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findAPIKeyByKeyHash = `-- name: FindAPIKeyByKeyHash :one
SELECT id, user_id, name, key_prefix, key_hash, scopes, status, tenant_id, expires_at, last_used_at, created_at, revoked_at
FROM api_keys
WHERE key_hash = $1
`

func (q *Queries) FindAPIKeyByKeyHash(ctx context.Context, keyHash string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, findAPIKeyByKeyHash, keyHash)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Status,
		&i.TenantID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findAPIKeyByPrefix = `-- name: FindAPIKeyByPrefix :one
SELECT id, user_id, name, key_prefix, key_hash, scopes, status, tenant_id, expires_at, last_used_at, created_at, revoked_at
FROM api_keys
WHERE key_prefix = $1
`

func (q *Queries) FindAPIKeyByPrefix(ctx context.Context, keyPrefix string) (ApiKey, error) {
	row := q.db.QueryRow(ctx, findAPIKeyByPrefix, keyPrefix)
	var i ApiKey
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.KeyPrefix,
		&i.KeyHash,
		&i.Scopes,
		&i.Status,
		&i.TenantID,
		&i.ExpiresAt,
		&i.LastUsedAt,
		&i.CreatedAt,
		&i.RevokedAt,
	)
	return i, err
}

const findActiveAPIKeysByUserID = `-- name: FindActiveAPIKeysByUserID :many
SELECT id, user_id, name, key_prefix, key_hash, scopes, status, tenant_id, expires_at, last_used_at, created_at, revoked_at
FROM api_keys
WHERE user_id = $1
  AND status = 'active'
  AND (expires_at IS NULL OR expires_at > NOW())
ORDER BY created_at DESC
`

func (q *Queries) FindActiveAPIKeysByUserID(ctx context.Context, userID string) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, findActiveAPIKeysByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.Status,
			&i.TenantID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAPIKeys = `-- name: ListAPIKeys :many
SELECT id, user_id, name, key_prefix, key_hash, scopes, status, tenant_id, expires_at, last_used_at, created_at, revoked_at
FROM api_keys
WHERE ($3::text IS NULL OR user_id = $3)
  AND ($4::text IS NULL OR tenant_id = $4)
  AND ($5::text IS NULL OR status = $5)
  AND ($6::bool = FALSE OR (status = 'active' AND (expires_at IS NULL OR expires_at > NOW())))
ORDER BY
    CASE WHEN $7 = 'created_at' AND $8 = 'asc' THEN created_at END ASC,
    CASE WHEN $7 = 'created_at' AND $8 = 'desc' THEN created_at END DESC,
    CASE WHEN $7 = 'last_used_at' AND $8 = 'asc' THEN last_used_at END ASC NULLS LAST,
    CASE WHEN $7 = 'last_used_at' AND $8 = 'desc' THEN last_used_at END DESC NULLS LAST,
    CASE WHEN $7 = 'name' AND $8 = 'asc' THEN name END ASC,
    CASE WHEN $7 = 'name' AND $8 = 'desc' THEN name END DESC,
    CASE WHEN $7 = 'expires_at' AND $8 = 'asc' THEN expires_at END ASC NULLS LAST,
    CASE WHEN $7 = 'expires_at' AND $8 = 'desc' THEN expires_at END DESC NULLS LAST,
    created_at DESC
LIMIT $1 OFFSET $2
`

type ListAPIKeysParams struct {
	Limit      int32       `json:"limit"`
	Offset     int32       `json:"offset"`
	UserID     pgtype.Text `json:"user_id"`
	TenantID   pgtype.Text `json:"tenant_id"`
	Status     pgtype.Text `json:"status"`
	ActiveOnly bool        `json:"active_only"`
	SortBy     interface{} `json:"sort_by"`
	SortOrder  interface{} `json:"sort_order"`
}

func (q *Queries) ListAPIKeys(ctx context.Context, arg ListAPIKeysParams) ([]ApiKey, error) {
	rows, err := q.db.Query(ctx, listAPIKeys,
		arg.Limit,
		arg.Offset,
		arg.UserID,
		arg.TenantID,
		arg.Status,
		arg.ActiveOnly,
		arg.SortBy,
		arg.SortOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ApiKey{}
	for rows.Next() {
		var i ApiKey
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.KeyPrefix,
			&i.KeyHash,
			&i.Scopes,
			&i.Status,
			&i.TenantID,
			&i.ExpiresAt,
			&i.LastUsedAt,
			&i.CreatedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const revokeAPIKeyByID = `-- name: RevokeAPIKeyByID :exec
UPDATE api_keys
SET status = 'revoked', revoked_at = NOW()
WHERE id = $1 AND status = 'active'
`

func (q *Queries) RevokeAPIKeyByID(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, revokeAPIKeyByID, id)
	return err
}

const revokeAllAPIKeysByUserID = `-- name: RevokeAllAPIKeysByUserID :execrows
UPDATE api_keys
SET status = 'revoked', revoked_at = NOW()
WHERE user_id = $1 AND status = 'active'
`

func (q *Queries) RevokeAllAPIKeysByUserID(ctx context.Context, userID string) (int64, error) {
	result, err := q.db.Exec(ctx, revokeAllAPIKeysByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAPIKey = `-- name: UpdateAPIKey :exec
UPDATE api_keys
SET name = $2, scopes = $3, status = $4, last_used_at = $5, revoked_at = $6
WHERE id = $1
`

type UpdateAPIKeyParams struct {
	ID         string             `json:"id"`
	Name       string             `json:"name"`
	Scopes     []string           `json:"scopes"`
	Status     string             `json:"status"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

func (q *Queries) UpdateAPIKey(ctx context.Context, arg UpdateAPIKeyParams) error {
	_, err := q.db.Exec(ctx, updateAPIKey,
		arg.ID,
		arg.Name,
		arg.Scopes,
		arg.Status,
		arg.LastUsedAt,
		arg.RevokedAt,
	)
	return err
}

const updateAPIKeyLastUsed = `-- name: UpdateAPIKeyLastUsed :exec
UPDATE api_keys
SET last_used_at = NOW()
WHERE id = $1
`

func (q *Queries) UpdateAPIKeyLastUsed(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, updateAPIKeyLastUsed, id)
	return err
}
