// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: challenges.sql

package sqlc

import (
	"context"
	"time"
)

const createChallenge = `-- name: CreateChallenge :exec
INSERT INTO challenges (id, did, nonce, purpose, expires_at, created_at)
VALUES ($1, $2, $3, $4, $5, $6)
`

type CreateChallengeParams struct {
	ID        string    `json:"id"`
	Did       string    `json:"did"`
	Nonce     string    `json:"nonce"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

func (q *Queries) CreateChallenge(ctx context.Context, arg CreateChallengeParams) error {
	_, err := q.db.Exec(ctx, createChallenge,
		arg.ID,
		arg.Did,
		arg.Nonce,
		arg.Purpose,
		arg.ExpiresAt,
		arg.CreatedAt,
	)
	return err
}

const deleteChallenge = `-- name: DeleteChallenge :exec
DELETE FROM challenges
WHERE id = $1
`

func (q *Queries) DeleteChallenge(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteChallenge, id)
	return err
}

const deleteChallengesByDID = `-- name: DeleteChallengesByDID :exec
DELETE FROM challenges
WHERE did = $1
`

func (q *Queries) DeleteChallengesByDID(ctx context.Context, did string) error {
	_, err := q.db.Exec(ctx, deleteChallengesByDID, did)
	return err
}

const deleteExpiredChallenges = `-- name: DeleteExpiredChallenges :execrows
DELETE FROM challenges
WHERE expires_at < NOW()
`

func (q *Queries) DeleteExpiredChallenges(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, deleteExpiredChallenges)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const findChallengeByID = `-- name: FindChallengeByID :one
SELECT id, did, nonce, purpose, expires_at, created_at
FROM challenges
WHERE id = $1
`

func (q *Queries) FindChallengeByID(ctx context.Context, id string) (Challenge, error) {
	row := q.db.QueryRow(ctx, findChallengeByID, id)
	var i Challenge
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.Nonce,
		&i.Purpose,
		&i.ExpiresAt,
		&i.CreatedAt,
	)
	return i, err
}
