// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

type ApiKey struct {
	ID         string             `json:"id"`
	UserID     string             `json:"user_id"`
	Name       string             `json:"name"`
	KeyPrefix  string             `json:"key_prefix"`
	KeyHash    string             `json:"key_hash"`
	Scopes     []string           `json:"scopes"`
	Status     string             `json:"status"`
	TenantID   pgtype.Text        `json:"tenant_id"`
	ExpiresAt  pgtype.Timestamptz `json:"expires_at"`
	LastUsedAt pgtype.Timestamptz `json:"last_used_at"`
	CreatedAt  time.Time          `json:"created_at"`
	RevokedAt  pgtype.Timestamptz `json:"revoked_at"`
}

type OAuthIdentity struct {
	ID             string      `json:"id"`
	UserID         string      `json:"user_id"`
	Provider       string      `json:"provider"`
	ProviderUserID string      `json:"provider_user_id"`
	Email          string      `json:"email"`
	Name           pgtype.Text `json:"name"`
	PictureUrl     pgtype.Text `json:"picture_url"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

type Challenge struct {
	ID        string    `json:"id"`
	Did       string    `json:"did"`
	Nonce     string    `json:"nonce"`
	Purpose   string    `json:"purpose"`
	ExpiresAt time.Time `json:"expires_at"`
	CreatedAt time.Time `json:"created_at"`
}

type Session struct {
	ID               string             `json:"id"`
	UserID           string             `json:"user_id"`
	UserDid          string             `json:"user_did"`
	TenantID         pgtype.Text        `json:"tenant_id"`
	RefreshTokenHash string             `json:"refresh_token_hash"`
	ExpiresAt        time.Time          `json:"expires_at"`
	CreatedAt        time.Time          `json:"created_at"`
	RevokedAt        pgtype.Timestamptz `json:"revoked_at"`
}

type User struct {
	ID        string      `json:"id"`
	Did       string      `json:"did"`
	Email     pgtype.Text `json:"email"`
	Name      pgtype.Text `json:"name"`
	Status    string      `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}
