// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: oauth_identities.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countOAuthIdentitiesByUserID = `-- name: CountOAuthIdentitiesByUserID :one
SELECT COUNT(*)
FROM oauth_identities
WHERE user_id = $1
`

func (q *Queries) CountOAuthIdentitiesByUserID(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countOAuthIdentitiesByUserID, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createOAuthIdentity = `-- name: CreateOAuthIdentity :exec
INSERT INTO oauth_identities (id, user_id, provider, provider_user_id, email, name, picture_url, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type CreateOAuthIdentityParams struct {
	ID             string      `json:"id"`
	UserID         string      `json:"user_id"`
	Provider       string      `json:"provider"`
	ProviderUserID string      `json:"provider_user_id"`
	Email          string      `json:"email"`
	Name           pgtype.Text `json:"name"`
	PictureUrl     pgtype.Text `json:"picture_url"`
	CreatedAt      time.Time   `json:"created_at"`
	UpdatedAt      time.Time   `json:"updated_at"`
}

func (q *Queries) CreateOAuthIdentity(ctx context.Context, arg CreateOAuthIdentityParams) error {
	_, err := q.db.Exec(ctx, createOAuthIdentity,
		arg.ID,
		arg.UserID,
		arg.Provider,
		arg.ProviderUserID,
		arg.Email,
		arg.Name,
		arg.PictureUrl,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteOAuthIdentity = `-- name: DeleteOAuthIdentity :exec
DELETE FROM oauth_identities
WHERE id = $1
`

func (q *Queries) DeleteOAuthIdentity(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteOAuthIdentity, id)
	return err
}

const deleteOAuthIdentityByUserIDAndProvider = `-- name: DeleteOAuthIdentityByUserIDAndProvider :exec
DELETE FROM oauth_identities
WHERE user_id = $1 AND provider = $2
`

func (q *Queries) DeleteOAuthIdentityByUserIDAndProvider(ctx context.Context, userID string, provider string) error {
	_, err := q.db.Exec(ctx, deleteOAuthIdentityByUserIDAndProvider, userID, provider)
	return err
}

const findOAuthIdentitiesByUserID = `-- name: FindOAuthIdentitiesByUserID :many
SELECT id, user_id, provider, provider_user_id, email, name, picture_url, created_at, updated_at
FROM oauth_identities
WHERE user_id = $1
ORDER BY created_at ASC
`

func (q *Queries) FindOAuthIdentitiesByUserID(ctx context.Context, userID string) ([]OAuthIdentity, error) {
	rows, err := q.db.Query(ctx, findOAuthIdentitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OAuthIdentity{}
	for rows.Next() {
		var i OAuthIdentity
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Provider,
			&i.ProviderUserID,
			&i.Email,
			&i.Name,
			&i.PictureUrl,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const findOAuthIdentityByID = `-- name: FindOAuthIdentityByID :one
SELECT id, user_id, provider, provider_user_id, email, name, picture_url, created_at, updated_at
FROM oauth_identities
WHERE id = $1
`

func (q *Queries) FindOAuthIdentityByID(ctx context.Context, id string) (OAuthIdentity, error) {
	row := q.db.QueryRow(ctx, findOAuthIdentityByID, id)
	var i OAuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOAuthIdentityByProviderAndProviderUserID = `-- name: FindOAuthIdentityByProviderAndProviderUserID :one
SELECT id, user_id, provider, provider_user_id, email, name, picture_url, created_at, updated_at
FROM oauth_identities
WHERE provider = $1 AND provider_user_id = $2
`

func (q *Queries) FindOAuthIdentityByProviderAndProviderUserID(ctx context.Context, provider string, providerUserID string) (OAuthIdentity, error) {
	row := q.db.QueryRow(ctx, findOAuthIdentityByProviderAndProviderUserID, provider, providerUserID)
	var i OAuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findOAuthIdentityByUserIDAndProvider = `-- name: FindOAuthIdentityByUserIDAndProvider :one
SELECT id, user_id, provider, provider_user_id, email, name, picture_url, created_at, updated_at
FROM oauth_identities
WHERE user_id = $1 AND provider = $2
`

func (q *Queries) FindOAuthIdentityByUserIDAndProvider(ctx context.Context, userID string, provider string) (OAuthIdentity, error) {
	row := q.db.QueryRow(ctx, findOAuthIdentityByUserIDAndProvider, userID, provider)
	var i OAuthIdentity
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Provider,
		&i.ProviderUserID,
		&i.Email,
		&i.Name,
		&i.PictureUrl,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
