// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package sqlc

import (
	"context"
	"time"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*)
FROM users
WHERE ($1::text IS NULL OR status = $1)
`

func (q *Queries) CountUsers(ctx context.Context, status pgtype.Text) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers, status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createUser = `-- name: CreateUser :exec
INSERT INTO users (id, did, email, name, status, created_at, updated_at)
VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type CreateUserParams struct {
	ID        string      `json:"id"`
	Did       string      `json:"did"`
	Email     pgtype.Text `json:"email"`
	Name      pgtype.Text `json:"name"`
	Status    string      `json:"status"`
	CreatedAt time.Time   `json:"created_at"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) error {
	_, err := q.db.Exec(ctx, createUser,
		arg.ID,
		arg.Did,
		arg.Email,
		arg.Name,
		arg.Status,
		arg.CreatedAt,
		arg.UpdatedAt,
	)
	return err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users
WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const existsByDID = `-- name: ExistsByDID :one
SELECT EXISTS(SELECT 1 FROM users WHERE did = $1)
`

func (q *Queries) ExistsByDID(ctx context.Context, did string) (bool, error) {
	row := q.db.QueryRow(ctx, existsByDID, did)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const existsByEmail = `-- name: ExistsByEmail :one
SELECT EXISTS(SELECT 1 FROM users WHERE email = $1)
`

func (q *Queries) ExistsByEmail(ctx context.Context, email pgtype.Text) (bool, error) {
	row := q.db.QueryRow(ctx, existsByEmail, email)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const findUserByDID = `-- name: FindUserByDID :one
SELECT id, did, email, name, status, created_at, updated_at
FROM users
WHERE did = $1
`

func (q *Queries) FindUserByDID(ctx context.Context, did string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByDID, did)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByEmail = `-- name: FindUserByEmail :one
SELECT id, did, email, name, status, created_at, updated_at
FROM users
WHERE email = $1
`

func (q *Queries) FindUserByEmail(ctx context.Context, email pgtype.Text) (User, error) {
	row := q.db.QueryRow(ctx, findUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const findUserByID = `-- name: FindUserByID :one
SELECT id, did, email, name, status, created_at, updated_at
FROM users
WHERE id = $1
`

func (q *Queries) FindUserByID(ctx context.Context, id string) (User, error) {
	row := q.db.QueryRow(ctx, findUserByID, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.Did,
		&i.Email,
		&i.Name,
		&i.Status,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsers = `-- name: ListUsers :many
SELECT id, did, email, name, status, created_at, updated_at
FROM users
WHERE ($3::text IS NULL OR status = $3)
ORDER BY
    CASE WHEN $4 = 'created_at' AND $5 = 'asc' THEN created_at END ASC,
    CASE WHEN $4 = 'created_at' AND $5 = 'desc' THEN created_at END DESC,
    CASE WHEN $4 = 'updated_at' AND $5 = 'asc' THEN updated_at END ASC,
    CASE WHEN $4 = 'updated_at' AND $5 = 'desc' THEN updated_at END DESC,
    CASE WHEN $4 = 'email' AND $5 = 'asc' THEN email END ASC,
    CASE WHEN $4 = 'email' AND $5 = 'desc' THEN email END DESC,
    created_at DESC
LIMIT $1 OFFSET $2
`

type ListUsersParams struct {
	Limit     int32       `json:"limit"`
	Offset    int32       `json:"offset"`
	Status    pgtype.Text `json:"status"`
	SortBy    interface{} `json:"sort_by"`
	SortOrder interface{} `json:"sort_order"`
}

func (q *Queries) ListUsers(ctx context.Context, arg ListUsersParams) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsers,
		arg.Limit,
		arg.Offset,
		arg.Status,
		arg.SortBy,
		arg.SortOrder,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.Did,
			&i.Email,
			&i.Name,
			&i.Status,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :exec
UPDATE users
SET email = $2, name = $3, status = $4, updated_at = $5
WHERE id = $1
`

type UpdateUserParams struct {
	ID        string      `json:"id"`
	Email     pgtype.Text `json:"email"`
	Name      pgtype.Text `json:"name"`
	Status    string      `json:"status"`
	UpdatedAt time.Time   `json:"updated_at"`
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) error {
	_, err := q.db.Exec(ctx, updateUser,
		arg.ID,
		arg.Email,
		arg.Name,
		arg.Status,
		arg.UpdatedAt,
	)
	return err
}
